
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import ThemeInitializer from '@/components/ThemeInitializer';
import GlobalLoadingOverlay from '@/components/GlobalLoadingOverlay';
import ClientRoot from '@/components/ClientRoot';
import ChatBox from '@/components/ChatBox';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'WordRush',
  description: 'A sleek and interactive typing test app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/png" href="/wordrush-large.png" />
      </head>
      <body className={inter.className}>
        <ThemeInitializer />
        <GlobalLoadingOverlay />
        <ClientRoot>
          {children}
        </ClientRoot>
        <ChatBox />
      </body>
    </html>
  );
}


// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
